@startuml

class LCD <<boundery>> {
    +test()
    +push(data)
}
class IrSensor <<boundery>> {
    +get()
}
class IrLed <<boundery>> {
    +send(byte data[2])
}
class Button <<boundery>> {
    +get()
}
class Speaker <<boundery>> {
    +play(sound, duration)
}
class KeyPad <<boundery>> {
    +get()
}

class DisplayController <<controller>> {
    -LCD dysplay
    +setTime(int time)
    +setScore(int scaore)
    +setWapen(int wapen)
    +setPlayerId(int id)
}
class IrReceiver <<controller>> {
    -IrSensor ir
    -RegisterController register
    -GameController game
}
class IrSender <<controller>> {
    -IrLed ir
    +fire(byte data)
    +command(command)
}
class ButtonController <<controller>> {
    -Button btn
    -IrSender ir
    -SoundController sound
    +setPlayerData(byte data[2])
    +setWapen(wapen)
    +disable()
    +enable()
}
class SoundController <<controller>> {
    -Speaker speaker
    +fire()
}
class KeyPadController <<controller>> {
    -KeyPad pad
    -InitController init
}

class PcProxy <<proxy>> {
    -GameController game
}

class GameController <<controller>> {
    -ButtonController btn
    -score[]
    -wapen
    -gameMode

    +getWapen()
    +getGameMode()

    +shot(score)
    +disable()
    +enable()
}
class GameTimeController <<controller>> {
    -GameController game
    -DisplayController display
    +start(int time)
    +stop()
}
class InitController <<controller>> {
    -IrSender ir
    +startGame()
    +stopGame()
    +setWapen(wapen)
    +setTimae(int time)
}
class RegisterController <<controller>> {
    -GameTimeController timer
    +startGame(int time)
    +stopGame()

    +setWapen(wapen)
    +setGameMode(mode)
}

enum Wapens <<entity>>
enum GameModes <<entity>>

DisplayController -> LCD
IrSensor <-- IrReceiver
IrLed <-- IrSender
Button <- ButtonController
Speaker <-- SoundController
KeyPad <-- KeyPadController

IrReceiver --> RegisterController
RegisterController --|> GameController

RegisterController -> GameTimeController
GameTimeController --> GameController
GameTimeController --> DisplayController
GameController -> DisplayController
'InitController --> GameController

IrSender <-- ButtonController
IrSender <-- InitController
KeyPadController --> InitController

ButtonController <- GameController
SoundController <-- ButtonController

GameController --> Wapens
GameController --> GameModes
GameController <-- PcProxy

@enduml