@startuml

class IrReceiver{
-dataToSend
+receive()
}
class IrSender{
-receivedData
+receive()
-decode()
}
class LCD {
+test()
+push(data)
}
class Sound{
+start(sound, duration)
}
class Fire{
-getButton()
}
class Console{
}
class DataController{
-score
-wapen
-gameMode
+addScore(score)
+setWapen(wapen)
+getWapen()
+setGameMode()
+getGameMode()
}
class GameTimeController{
+start()
+pause()
+resume()
+stop()
}

enum Wapens
enum GameModes


GameModes ..> DataController: <include>
Wapens ..> DataController: <include>
Fire <.. DataController: <include>
Console <.. DataController: <include>
LCD <-- DataController
GameTimeController <.. DataController: <include>
GameTimeController --> LCD
GameTimeController --|> Fire
IrReceiver --> DataController
Sound <-- Fire
IrSender <-- Fire

@enduml