@startuml

class IrReceiver{
-dataToSend
+receive()
}
class IrSender{
-receivedData
+receive()
-decode()
}
class Display_controller {
+test()
+push(data)
}
class Sound_Controller{
+start(sound, duration)
}
class Wifi_Controller{

}
class Fire{
-getButton()
}
class Console{
}
class Data_Controller{
-score
-lives
-wapen
-gameMode
+addScore(score)
+setLives(lives)
+lowerLive()
+setWapen(wapen)
+getWapen()
+setGameMode()
+getGameMode()
}

enum Wapens
enum GameModes


Console <|-- Data_Controller
Wifi_Controller --|> Data_Controller
Display_controller --|> Data_Controller
IrReceiver --|> Data_Controller
IrSender <|-- Fire
Fire <|-- Data_Controller
Wapens --|> Data_Controller
GameModes --|> Data_Controller
Sound_Controller <|-- Fire

'class ArrayList {
'Object[] elementData
'size()
'}

@enduml