#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := IRReceiver.cpp IRSender.cpp DisplayController.cpp KeyPadController.cpp InitController.cpp SpeakerController.cpp GameController.cpp GameTimeController.cpp

# header files in this project
HEADERS := IRReceiver.hpp IRSender.hpp DisplayController.hpp KeyPadController.hpp InitController.hpp SpeakerController.hpp GameController.hpp GameTimeController.hpp Weapons.hpp Gamemodes.hpp

# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
